name: blinky

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Target_Cortex-M0
      run: rustup target add thumbv6m-none-eabi
    - name: install flip-link
      run: cargo install flip-link
    - name: Build
      run: cargo build --release
